import os

DB_NAME="cho"
DB_PATH="cho"
DB_USER = os.getenv("DB_USER")
DB_HOST= os.getenv("DB_HOST")
DB_PASSWORD= os.getenv("DB_PASSWORD")
DB_PORT="5432"  # Default

N_ITENS = 40
N_CLIENTES = 50
MAX_NUM_TELEFONE = 3
PROB_ENFERMIDADE = 0.3
N_INGREDIENTES = 25
N_FILIAIS = 5
N_FORNECEDORES = 10
N_FUNCIONARIOS = 30
MAX_INGREDIENTES = 20
N_RESERVAS = 60
MAX_MESAS = 20
N_PEDIDOS = 120
MAX_QTD = 5
MAX_ITENS = 4